# Generated by Django 3.0.5 on 2020-04-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_login_provider",
            field=models.CharField(
                blank=True,
                choices=[("facebook", "Facebook"), ("google", "Google")],
                default="",
                max_length=256,
            ),
        ),
    ]
