services:
  backend:
    build: &build
      context: backend
      dockerfile: Dockerfile.local
    depends_on: &depends_on
      - db
      - cache
    volumes: &volumes
      - ./backend:/code
  cache:
    image: redis
    ports:
      - 6379:6379
  db:
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres:11
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.local
    volumes:
      - ./frontend:/code
      - /code/node_modules
      - /code/.next
  reverse-proxy:
    depends_on:
      - frontend
      - backend
    image: caddy
    ports:
      - 3001:3001
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  worker:
    build: *build
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery
      -A backend worker --loglevel=INFO
    depends_on: *depends_on
    volumes: *volumes
version: '3.4'
x-backend-app:
  build: *build
  depends_on: *depends_on
  volumes: *volumes
