INVALID_PASSWORD = "invalid_password"
AUTH_FAILURE = "auth_failure"
INVALID_TOKEN = "invalid_token"
INVALID_EMAIL = "invalid_email"
AUTH_CHANGE_LOCKOUT = "auth_change_lockout"
EMAIL_EXISTS = "email_exists"
